# Generated by Django 3.1.6 on 2021-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinemessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
